<a href="https://colab.research.google.com/github/FajarWahyuni/Learn-ML/blob/main/Data_Preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
# Step 1. Importing the useful packages
import numpy as np
from sklearn import preprocessing


* Numpy : general purpose array-processing package designed to efficiently manipulate large multi-dimensional arrays of arbitrary records without sacrificing too much speed for small multi-dimensional arrays.
* Sklearn.preprocessing : provides many common utility functions and tranformer classes to change raw feature vectors into a representation that is more suitable for ml algorithms.

In [6]:
# Step 2. Defining sample data
input_data = np.array([
    [2.1, -1.9, 5.5],
    [-1.5, 2.4, 3.5],
    [0.5, -7.9, 5.6],
    [5.9, 2.3, -5.8]
])

In [ ]:
# Step 3. Applying preprocessing technique

Teknik untuk data preprocessing diantaranya:
1. Binarization : digunakan ketika kita ingin convert data numerical values into Boolean values.

In [11]:
# Binarization
data_binarized = preprocessing.Binarizer(threshold = 0.5).transform(input_data)

In [12]:
print("\nBinarized Data:\n", data_binarized)


Binarized Data:
 [[1. 0. 1.]
 [0. 1. 1.]
 [0. 0. 1.]
 [1. 1. 0.]]


Seluruh nilai yang di atas 0.5 akan bernilai 1, sedangkan nilai dibawah 0.5 dikonversi menjadi 0.

In [13]:
# Mean Removal
# Basically it is used to eliminate the mean from feature vector so that every feature is centered on zero.
# We can also remove the bias from the features in the feature vector.
print("Mean =", input_data.mean(axis = 0))
print("STD =", input_data.std(axis = 0))

Mean = [ 1.75  -1.275  2.2  ]
STD = [2.71431391 4.20022321 4.69414529]


Selanjutnya kode berikut akan menghapus rata-rata dan std dari input_data

In [15]:
data_scaled = preprocessing.scale(input_data)
print("Mean =", data_scaled.mean(axis = 0))
print("STD =", data_scaled.std(axis = 0))

Mean = [1.11022302e-16 0.00000000e+00 0.00000000e+00]
STD = [1. 1. 1.]


In [16]:
# Scalling
# it is used to scale the feature vectors
# it is needed bcs the values of every feature can vary between many random values.
# soo scaling is important bcs we do not want any feature to be synthetically large or small.
## MinMaxScalling
data_scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0,1))
data_scaled_minmax = data_scaler_minmax.fit_transform(input_data)
print ("\nMin max scaled data:\n", data_scaled_minmax)


Min max scaled data:
 [[0.48648649 0.58252427 0.99122807]
 [0.         1.         0.81578947]
 [0.27027027 0.         1.        ]
 [1.         0.99029126 0.        ]]


In [17]:
# Normalization
## L1 Normalization
## It is also referred to Least Absolute Deviations. modify the values so that the sum of the absolute values always up to 1 in each row.
normalized_data_l1 = preprocessing.normalize(input_data, norm = 'l1')
print("\nL1 normalized data :\n", normalized_data_l1)


L1 normalized data :
 [[ 0.22105263 -0.2         0.57894737]
 [-0.2027027   0.32432432  0.47297297]
 [ 0.03571429 -0.56428571  0.4       ]
 [ 0.42142857  0.16428571 -0.41428571]]


In [18]:
## L2 Normalization
## Referred to as least squares, modify the values so that the sum of the squares is always up to 1 in each row.
normalized_data_l2 = preprocessing.normalize(input_data, norm = 'l2')
print("\nL1 normalized data :\n", normalized_data_l2)


L1 normalized data :
 [[ 0.33946114 -0.30713151  0.88906489]
 [-0.33325106  0.53320169  0.7775858 ]
 [ 0.05156558 -0.81473612  0.57753446]
 [ 0.68706914  0.26784051 -0.6754239 ]]


In [23]:
# Labelling Data
## Label encoding steps
### 1. Import packages (sama kaya yang atas ko)
from sklearn.preprocessing import LabelEncoder
### 2. Defining sample
input_labels = ['red', 'green', 'black', 'red', 'yellow', 'white']

In [26]:
### 3. Creating and training of label encoder objects
Encoder = preprocessing.LabelEncoder()
Encoder.fit(input_labels)

LabelEncoder()

In [27]:
### 4. Checking the performance by encoding random ordered list
test_labels = ['green', 'red', 'black']
encoded_values = Encoder.transform(test_labels)
print("\nLabels =", test_labels)


Labels = ['green', 'red', 'black']


In [28]:
print("Encoded values = ", list(encoded_values))

Encoded values =  [1, 2, 0]


In [29]:
### 5. Checking the performance by decoding a random set of numbers
encoded_values = [3,0,4,1]
decoded_list = Encoder.inverse_transform(encoded_values)
print("\nEncoded Values =", encoded_values)


Encoded Values = [3, 0, 4, 1]


In [30]:
print("Decoded Labels = ", list(decoded_list))

Decoded Labels =  ['white', 'black', 'yellow', 'green']
